---
- hosts: localhost
  tasks:
  - name: check ansible version for ansible == 2.5.2
    assert:
        that:
            - ansible_version.major == 2
            - ansible_version.minor == 5
            - ansible_version.revision == 2
        msg: "You must install Ansible 2.5.2 to continue"

- hosts: OSEv3
  tasks:
  - name: Install base packages
    yum: name="{{ item }}" state=present
    with_items:
    - wget
    - net-tools
    - bind-utils
    - iptables-services
    - bridge-utils
    - bash-completion
    - git
    - python-pip
    - kexec-tools
    - sos
    - psacct
    - ntp
    - NetworkManager
    - python-netaddr

  - name: Install Openshift Enterprise package
    yum: name="{{ item }}" state=present
    with_items:
    - atomic-openshift-docker-excluder
    when:
    - deployment_type == "openshift-enterprise"

  - name: Install docker-py
    command: pip install docker-py
    when:
    - deployment_type == "openshift-enterprise"

  - fail:
      msg: "Need a higher version of docker"
    when:
        - docker_version is defined
        - "{{ docker_version is version('1.13.1', '<') }}"

  - name: install docker
    yum:
      name: "docker-{{ docker_version | default('1.13.1')}}"
      state: installed

  - name: Enable Docker Service
    service: name=docker enabled=yes

  - name: Check NetworkManager enabled
    service: name=NetworkManager enabled=yes

  - name: Start Docker Service
    service: name=docker state=started

  - name: Start NetworkManager
    service: name=NetworkManager state=started

  - name: Start Ntp Service
    service: name=ntpd state=started
